### ISSUE TITLE
Copying simulation files with selfscripted Gazebo PlungIns

### ISSUE THREAD

**Issue by Euleeee** [FieldRobotEvent/competition_environment#16]
Hello to everyone,

our FRE Team has a few problems while copying simulation files with the _copy_simulation_files.py_. 

### Initial Situation ### 
During the last years our team developed a real robot with a passive articulated joint and we want to simulate our robot due to the hybrid event. We started to get familiar with Gazebo for the last three months and created a URDF Model of our robot with two Sick Scan LIDARS and two Intel Realsense Cameras. The Sick Scan LIDARS use the Gazebo Laser plugin, but the Intel Realsense use their own plugin to use all the features. 
The kinematic calculations for our robot are done in an extra ROS package which listens to the actual wheel speed and the angle of the articulated joint and publishs the speed of every wheel. Gazebo listens to the published messages with a selfscripted plugin and sets the velocitys of the individual wheels.

### Problem ### 
Now we want to test our robot simulation in the competion environment with docker. But when we want to copy the simulation files the Python script stops and says that no Gazbo plungins are allowed except to the sensor plugins. Is it possible to allow the Intel Realsense Plugin or do you know a workaround? And is there a way to set the wheel speed in the simulation without a Gazebo Plugin?

Thanks for your help!
Best regards Jonathan

**Comment by Rick-v-E** [comment]
Hi Jonathan,

If you want to use the Intel RealSense Plugin, please sent an email to info@fieldrobot.com. The organization will then decide to allow the plugin for the competition. If they allow the plugin, they will install the plugin in the simulation container and update the list of allowed Gazebo plugins. An alternative could be to use the `libgazebo_ros_openni_kinect.so` plugin for RGB-D cameras but I don't know if this gives you the output you need for your robot. See https://www.fieldrobot.com/event/index.php/contest-hybrid/tasks-h/ for more explanation. 

You can use the self-scripted plugin for setting the velocity of the individual wheels is fine. In order to let this work, we have to install this plugin to the simulation container. Therefore, you have to add this plugin to a public GitHub / GitLab repository and provide us the link. 

Alternatively, you can define a `velocity_controllers/JointVelocityController` controller for each of the wheel joints, 

```yaml
my_robot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  joint_1_controller:
    type: velocity_controllers/JointVelocityController
    joint: a_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_2_controller:
    type: velocity_controllers/JointVelocityController
    joint: b_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_3_controller:
    type: velocity_controllers/JointVelocityController
    joint: c_wheel
    pid: {p: 100.0, i: 0.01, d: 10.0}
 ...
```
, launch all controllers together,

```xml
<rosparam file="$(find my_package)/config/gazebo_control.yaml" command="load"/> 
<node name="controller_spawner" pkg="controller_manager" type="spawner" respawn="false" ns="my_robot"
    args="joint_state_controller
              joint_1_controller
              joint_2_controller
              joint_3_controller
             ...
            "/>
```
and publish the wheel velocity to the corresponding topic (`joint_1_controller/command`, `joint_2_controller/command`, `joint_3_controller/command`, ...).

Regards, 
Rick
